In [9]:
import numpy as np

In [68]:
def mark_line(matrix, coords):
    (x1, y1, x2, y2) = coords
    if x1 == x2:
        for j in range(min(y1,y2),max(y1,y2)+1):
            matrix[j,x1] += 1
    elif y1 == y2:
        for i in range(min(x1,x2),max(x1,x2)+1):
            matrix[y1,i] += 1
    else:
        y_min = min(y1,y2)
        # y_max = max(y1,y2)
        x_min = min(x1,x2)
        x_max = max(x1,x2)
        # print(x_min, x_max, y_min)
        if (x1-x2)*(y1-y2) > 0:
            for i in range(x_max-x_min+1):
                matrix[y_min+i, x_min+i] += 1
        else:
            # print("negative")
            for i in range(x_max-x_min+1):
                matrix[y_min+i, x_max-i] += 1
    # print(matrix)
    return matrix

In [69]:
with open("input.txt") as f:
    lines = f.read().splitlines()
    x_max = 0
    y_max = 0
    neat_lines = []
    for line in lines:
        start, end = line.split("->")
        x1,y1 = start.strip().split(",")
        x2,y2 = end.strip().split(",")
        
        x1,y1,x2,y2=int(x1),int(y1),int(x2),int(y2)
        neat_lines.append([x1,y1,x2,y2])
        x_max=max(x1,x2,x_max)
        y_max=max(y1,y2,y_max)
    grid = np.zeros((x_max+1,y_max+1))
    for line in neat_lines:
        # print(line)
        grid = mark_line(grid, line)
        # print(grid,"\n")
    print(grid)
    count = 0
    for row in grid:
        for elem in row:
            if elem >= 2:
                count += 1
    print(count)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
22083
